name: test dash output

on: 
  push:
    branches:
    - '**'

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      aaa-output1: ${{ steps.step1.outputs.aaa-test }}
      bbb-output2: ${{ steps.step2.outputs.bbb-test }}
    steps:
      - id: step1
        run: echo "aaa-test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "bbb-test=world and beyond" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.aaa-output1}} ${{needs.job1.outputs.bbb-output2}}
