name: test duplicate

on: 
  push:
    branches:
    - '**'
  pull_request:
    types:
    - synchronize
    - opened
    - reopened

env:
  GITHUB_REPOSITORY: Cicatrice/apodex

jobs:
  gate:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
  go:
    runs-on: ubuntu-latest
    steps:
     - run: |
        cat <<EOF
        github: ${{ toJSON(github) }}
        env: ${{ toJSON(env) }}
        job: ${{ toJSON(job) }}
        runner: ${{ toJSON(runner) }}
        needs: ${{ toJSON(needs) }}
        steps: ${{ toJSON(steps) }}
        EOF        
        echo done
        echo test sync
