name: test duplicate

on: 
  push:
    branches:
    - '**'
  pull_request:
    types:
    - synchronize
    - opened
    - reopened

env:
  GITHUB_REPOSITORY: Cicatrice/apodex

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ toJSON(github) }}
        echo ${{ toJSON(env) }}
        echo ${{ toJSON(job) }}
        echo ${{ toJSON(runner) }}
        echo ${{ toJSON(needs) }}
        echo ${{ toJSON(steps) }}

