name: test duplicate

on: 
  push:
    branches:
    - '**'
  pull_request:
    types:
    - synchronize
    - opened
    - reopened

env:
  GITHUB_REPOSITORY: Cicatrice/apodex

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: jwalton/gh-find-current-pr@v1
        id: find-pr

  go:
    runs-on: ubuntu-latest
    needs: gate
    if: ${{ !steps.find-pr.outputs.number }}
    steps:
     - run: |
        cat <<EOF
        github: ${{ toJSON(github) }}
        env: ${{ toJSON(env) }}
        job: ${{ toJSON(job) }}
        runner: ${{ toJSON(runner) }}
        needs: ${{ toJSON(needs) }}
        steps: ${{ toJSON(steps) }}
        EOF        
        echo done
        echo test sync
