name: test duplicate

on: 
  push:
    branches:
    - '**'

env:
  GITHUB_REPOSITORY: Cicatrice/apodex

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # Find the PR associated with this push, if there is one.
      - uses: Cicatrice/gh-find-open-prs@main
        id: findPr
      - run: |
          cat <<EOF
          steps: ${{ toJSON(steps.findPr) }}
          EOF
